export enum AgentType {
  DIRECTOR_AI = 'director_ai',
  ACCOUNTING_AI = 'accounting_ai',
  SALES_AI = 'sales_ai',
  MARKETING_AI = 'marketing_ai',
  HR_AI = 'hr_ai',
  STOCK_AI = 'stock_ai',
  DELIVERY_AI = 'delivery_ai',
  SUPPORT_AI = 'support_ai',
  LEGAL_AI = 'legal_ai',
  INNOVATION_AI = 'innovation_ai',
  CEO_PSYCHOLOGIST = 'ceo_psychologist',
  FRAUD_DETECTOR = 'fraud_detector',
  CRISIS_PREDICTOR = 'crisis_predictor',
  AFRICAN_MARKET = 'african_market',
  GLOBAL_SUPPLIERS = 'global_suppliers',
  NEGOTIATOR = 'negotiator',
  WEBSITE_CREATOR = 'website_creator',
  DESIGNER = 'designer',
  WHATSAPP_AGENT = 'whatsapp_agent',
  TRANSLATOR_AGENT = 'translator_agent',
  RECRUITMENT_AGENT = 'recruitment_agent',
  STRATEGY_AGENT = 'strategy_agent',
  FORECAST_AGENT = 'forecast_agent',
  CREDIT_AGENT = 'credit_agent',
  AI_UNIVERSITY = 'ai_university',
  FLEET_MANAGER = 'fleet_manager',
  DRIVER_MANAGER = 'driver_manager',
  FUEL_MANAGER = 'fuel_manager',
  MAINTENANCE_MANAGER = 'maintenance_manager',
  ROUTE_PLANNER = 'route_planner',
  PHARMACY_MANAGER = 'pharmacy_manager',
  PRESCRIPTION_MANAGER = 'prescription_manager',
  EXPIRY_MANAGER = 'expiry_manager',
  PATIENT_MANAGER = 'patient_manager',
  KITCHEN_MANAGER = 'kitchen_manager',
  MENU_MANAGER = 'menu_manager',
  RESERVATION_MANAGER = 'reservation_manager',
  FOOD_SUPPLIER_MANAGER = 'food_supplier_manager',
  CROP_MANAGER = 'crop_manager',
  LIVESTOCK_MANAGER = 'livestock_manager',
  WEATHER_ADVISOR = 'weather_advisor',
  CONSTRUCTION_MANAGER = 'construction_manager',
  PROJECT_MANAGER = 'project_manager',
  QUALITY_INSPECTOR = 'quality_inspector',
  TEXTILE_DESIGNER = 'textile_designer',
  PRODUCTION_MANAGER = 'production_manager',
  // Sports & clubs
  SPORTS_MANAGER = 'sports_manager',
  PLAYER_MANAGER = 'player_manager',
  TEAM_MANAGER = 'team_manager',
  TRAINING_PLANNER = 'training_planner',
  SPORTS_MARKETING = 'sports_marketing',
  TICKETING_AGENT = 'ticketing_agent',
  // Beauty & wellness
  BEAUTY_MANAGER = 'beauty_manager',
  APPOINTMENT_AGENT = 'appointment_agent',
  LOYALTY_AGENT = 'loyalty_agent',
  // Education
  EDUCATION_MANAGER = 'education_manager',
  STUDENT_MANAGER = 'student_manager',
  TEACHER_MANAGER = 'teacher_manager',
  // Hospitality
  HOTEL_MANAGER = 'hotel_manager',
  ROOM_MANAGER = 'room_manager',
  GUEST_RELATIONS = 'guest_relations',
  // Real estate
  REAL_ESTATE_MANAGER = 'real_estate_manager',
  PROPERTY_MANAGER = 'property_manager',
  // Social media
  SOCIAL_MEDIA_AGENT = 'social_media_agent',
  CONTENT_CREATOR = 'content_creator',
  // E-commerce
  ECOMMERCE_MANAGER = 'ecommerce_manager',
  ORDER_MANAGER = 'order_manager',
  // Analytics
  DATA_ANALYST = 'data_analyst',
  GROWTH_AGENT = 'growth_agent',
  // Billing
  BILLING_AGENT = 'billing_agent',
}
